<?
$PERM["pub"]["*"]="R";
$PERM["dokumenty"]["*"]="D";
$PERM["dokumenty"]["9"]="X";
$PERM["sale"]["10"]="T_8";
$PERM["sale"]["9"]="T_8";
$PERM["sale"]["*"]="D";
$PERM["manage"]["9"]="T_8";
$PERM["manage"]["*"]="D";
?>